Iter5
AntonPashechko/yametrix pull request #5
Opened 2023-04-13 09:23 UTC by AntonPashechko

2023-04-13 21:06 UTC, mshogin requested changes
Очень здорово! Понравился минималистичный подход к решению задачи. Классная архитектура приложения. С небольшими доработками вполне production-ready код.
Есть некоторые ньюансы. В целом очень круто.

2023-04-13 21:06 UTC, mshogin commented on pkg/utils/utils.go
> +func StrToInt64(str string) (int64, error) {
minor: не обязательная функция
использование strconv.ParseInt(str, 10, 64) достаточно стандартно
(для информации, не обязательно удалять)

2023-04-13 21:06 UTC, mshogin commented on pkg/utils/utils.go
> +func StrToFloat64(str string) (float64, error) {
minor: не обязательная функция
использование trconv.ParseFloat(str, 64) достаточно стандартно
(для информации, не обязательно удалять)

2023-04-16 10:07 UTC, AntonPashechko commented on internal/handlers/metrix/handler.go
> +	case "gauge":
А если вдруг будет ситуация, что в gauge и counter наборах существует метрика с одним именем?)
Понимаю, что врятли такое возможно. Исправил.

2023-04-16 10:12 UTC, AntonPashechko commented on cmd/server/main.go
> +func runServer(ctx context.Context) {
Пока закоментировал код обработки syscall.SIGINT, syscall.SIGTERM и историю с graceful, но хочу разобраться...

2023-04-16 10:12 UTC, AntonPashechko commented on cmd/server/main.go
> +	/*ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
Пока закоментировал, убрал из main()

2023-04-16 10:14 UTC, AntonPashechko commented on internal/handlers/metrix/handler_test.go
> +		t.Run(tt.name, func(t *testing.T) {
Исправил

2023-04-16 10:20 UTC, AntonPashechko commented on internal/handlers/metrix/handler.go
> +func (h *Handler) update(w http.ResponseWriter, r *http.Request) {
Здесь не очень понял, не могу сделать как в get, нужно понять какого типа метрика, что бы понять, какую мапу обновлять. Возможно я не понял что то.

2023-04-16 10:36 UTC, AntonPashechko commented on internal/agent/metrix/runtime.go
> +		return err
Сделал. Узнать подроблнее про цепочку ошибок 1х1

2023-04-16 10:57 UTC, AntonPashechko commented on internal/agent/metrix/runtime.go
> +	return rm.gauges, rm.counters
Спасибо, что пояснил. Реализовал DeepCopyMap

2023-04-16 11:09 UTC, AntonPashechko commented on internal/agent/shaduller/shaduller.go
> +package shaduller
Переименовал. С языком плохо да (

2023-04-16 11:11 UTC, AntonPashechko commented on internal/agent/client/metrixsender.go
> +		return err
Исправил

2023-04-16 11:20 UTC, AntonPashechko commented on cmd/agent/main.go
> +	pollShaduller.Stop()
Осознал, исправил

2023-04-16 11:35 UTC, AntonPashechko commented on pkg/utils/utils.go
> +func StrToFloat64(str string) (float64, error) {
А тут просто для аналогии с StrToInt64, пока оставлю так.

2023-04-16 11:35 UTC, AntonPashechko commented on pkg/utils/utils.go
> +func StrToInt64(str string) (int64, error) {
Не нравится громоздкость такой конструкции, пока base не изменен, предочту свой вариант.

2023-04-16 11:37 UTC, AntonPashechko commented on internal/agent/metrix/runtime.go
> +		if reflect.TypeOf(fields[gaugeName]).Kind() != reflect.Float64 {
Тут хочу проверить, что не запрашивается метрика которая не представлена в Runtime как float64.
А что не так с reflect?
Обсудить

2023-04-16 11:50 UTC, AntonPashechko commented on internal/agent/metrix/worker.go
> +type UpdateMetrixWorker struct {
Обсудить. Если работаем через интерфей можно не экспортировать?
Исправли у реализаторов RecurringWorker

2023-04-16 11:56 UTC, AntonPashechko commented on internal/agent/shaduller/shaduller.go
> +	ch     chan bool
Переименовал )

2023-04-16 11:57 UTC, AntonPashechko commented on internal/agent/shaduller/shaduller.go
> +	s.ch <- true
Честно, не понял в чем разница в итоге. Вроде поведение все равно будет одинаковое.
Обусудить

2023-04-18 16:09 UTC, AntonPashechko commented on internal/storage/mem_storage/storage.go
> +package memstorage
Сделал

2023-04-18 16:12 UTC, AntonPashechko commented on internal/storage/mem_storage/storage.go
> +func (m *MemStorage) GetMetrixList() []string {
Сделал

2023-04-18 16:34 UTC, AntonPashechko commented on internal/agent/shaduller/shaduller.go
> +func (s Shaduller) Start() {
Сделал

2023-04-18 17:14 UTC, AntonPashechko commented on internal/agent/metrix/runtime.go
> +package metrix
Сделал

2023-04-18 17:14 UTC, AntonPashechko commented on internal/agent/client/metrixsender.go
> +func (mhc *MetrixHTTPClient) Send() error {
Не знаю как тестировать, слишком много зависимостей, и тест получается слишком интерграционный, а не юнит ни разу.

2023-04-18 22:31 UTC, mshogin requested changes
Супер! Мне очень понравилась идея с шедулерами и concurrency. Есть некоторые моменты связанные с управлением зависимостями, которые предлагаю решить сразу.
Представляю два ревью:
полное: https://disk.yandex.ru/i/F6OCCDlIVsQudg
краткий обзор: https://disk.yandex.ru/i/-9j4BrYzp8-yww
Полное ревью предлагаю использовать как справочник почему были предложены те или иные изменения.
Рекомендую смотреть на скорости 1.5х - 2х
Отправлено на доработку.

2023-04-20 18:33 UTC, mshogin approved these changes
Отлично! Сделано просто классно! Спасибо за проделанную работу. Принято.

2023-04-20 22:43 UTC, merged